# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings_dialog.ui'
#
# Created: Thu Mar 19 11:46:05 2015
#      by: PyQt5 UI code generator 5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_settings_dialog(object):
    def setupUi(self, settings_dialog):
        settings_dialog.setObjectName("settings_dialog")
        settings_dialog.resize(774, 753)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(settings_dialog.sizePolicy().hasHeightForWidth())
        settings_dialog.setSizePolicy(sizePolicy)
        settings_dialog.setLocale(QtCore.QLocale(QtCore.QLocale.C, QtCore.QLocale.AnyCountry))
        self.verticalLayout = QtWidgets.QVBoxLayout(settings_dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabs = QtWidgets.QTabWidget(settings_dialog)
        self.tabs.setObjectName("tabs")
        self.tab_servers = QtWidgets.QWidget()
        self.tab_servers.setObjectName("tab_servers")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_servers)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.input_checkbutton_debug_mode = QtWidgets.QCheckBox(self.tab_servers)
        self.input_checkbutton_debug_mode.setObjectName("input_checkbutton_debug_mode")
        self.horizontalLayout_2.addWidget(self.input_checkbutton_debug_mode)
        self.input_checkbutton_debug_to_file = QtWidgets.QCheckBox(self.tab_servers)
        self.input_checkbutton_debug_to_file.setEnabled(True)
        self.input_checkbutton_debug_to_file.setObjectName("input_checkbutton_debug_to_file")
        self.horizontalLayout_2.addWidget(self.input_checkbutton_debug_to_file)
        self.input_entry_debug_file = QtWidgets.QLineEdit(self.tab_servers)
        self.input_entry_debug_file.setObjectName("input_entry_debug_file")
        self.horizontalLayout_2.addWidget(self.input_entry_debug_file)
        self.gridLayout.addLayout(self.horizontalLayout_2, 3, 1, 1, 3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.button_new_server = QtWidgets.QPushButton(self.tab_servers)
        self.button_new_server.setObjectName("button_new_server")
        self.verticalLayout_2.addWidget(self.button_new_server)
        self.button_edit_server = QtWidgets.QPushButton(self.tab_servers)
        self.button_edit_server.setObjectName("button_edit_server")
        self.verticalLayout_2.addWidget(self.button_edit_server)
        self.button_copy_server = QtWidgets.QPushButton(self.tab_servers)
        self.button_copy_server.setObjectName("button_copy_server")
        self.verticalLayout_2.addWidget(self.button_copy_server)
        self.button_delete_server = QtWidgets.QPushButton(self.tab_servers)
        self.button_delete_server.setObjectName("button_delete_server")
        self.verticalLayout_2.addWidget(self.button_delete_server)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 3, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.input_checkbutton_use_system_keyring = QtWidgets.QCheckBox(self.tab_servers)
        self.input_checkbutton_use_system_keyring.setObjectName("input_checkbutton_use_system_keyring")
        self.horizontalLayout_3.addWidget(self.input_checkbutton_use_system_keyring)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 1, 1, 3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_update_interval_seconds = QtWidgets.QLabel(self.tab_servers)
        self.label_update_interval_seconds.setObjectName("label_update_interval_seconds")
        self.horizontalLayout.addWidget(self.label_update_interval_seconds)
        self.spinBox = QtWidgets.QSpinBox(self.tab_servers)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout.addWidget(self.spinBox)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 1, 1, 3)
        self.listWidget = QtWidgets.QListWidget(self.tab_servers)
        self.listWidget.setObjectName("listWidget")
        self.gridLayout.addWidget(self.listWidget, 0, 1, 1, 2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.input_checkbutton_check_for_new_version = QtWidgets.QCheckBox(self.tab_servers)
        self.input_checkbutton_check_for_new_version.setObjectName("input_checkbutton_check_for_new_version")
        self.horizontalLayout_4.addWidget(self.input_checkbutton_check_for_new_version)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.button_check_for_new_version_now = QtWidgets.QPushButton(self.tab_servers)
        self.button_check_for_new_version_now.setObjectName("button_check_for_new_version_now")
        self.horizontalLayout_4.addWidget(self.button_check_for_new_version_now)
        self.gridLayout.addLayout(self.horizontalLayout_4, 4, 1, 1, 3)
        self.tabs.addTab(self.tab_servers, "")
        self.tab_display = QtWidgets.QWidget()
        self.tab_display.setObjectName("tab_display")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_display)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupbox_appearance = QtWidgets.QGroupBox(self.tab_display)
        self.groupbox_appearance.setObjectName("groupbox_appearance")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupbox_appearance)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.input_radiobutton_statusbar_floating = QtWidgets.QRadioButton(self.groupbox_appearance)
        self.input_radiobutton_statusbar_floating.setObjectName("input_radiobutton_statusbar_floating")
        self.verticalLayout_3.addWidget(self.input_radiobutton_statusbar_floating)
        self.input_radiobutton_appindicator = QtWidgets.QRadioButton(self.groupbox_appearance)
        self.input_radiobutton_appindicator.setObjectName("input_radiobutton_appindicator")
        self.verticalLayout_3.addWidget(self.input_radiobutton_appindicator)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.input_radiobutton_icon_in_systray = QtWidgets.QRadioButton(self.groupbox_appearance)
        self.input_radiobutton_icon_in_systray.setObjectName("input_radiobutton_icon_in_systray")
        self.horizontalLayout_6.addWidget(self.input_radiobutton_icon_in_systray)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_systray_popup_offset = QtWidgets.QLabel(self.groupbox_appearance)
        self.label_systray_popup_offset.setObjectName("label_systray_popup_offset")
        self.horizontalLayout_7.addWidget(self.label_systray_popup_offset)
        self.spinBox_2 = QtWidgets.QSpinBox(self.groupbox_appearance)
        self.spinBox_2.setObjectName("spinBox_2")
        self.horizontalLayout_7.addWidget(self.spinBox_2)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_7)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.input_radiobutton_fullscreen = QtWidgets.QRadioButton(self.groupbox_appearance)
        self.input_radiobutton_fullscreen.setObjectName("input_radiobutton_fullscreen")
        self.horizontalLayout_16.addWidget(self.input_radiobutton_fullscreen)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.input_combo_fullscreen_display = QtWidgets.QLabel(self.groupbox_appearance)
        self.input_combo_fullscreen_display.setObjectName("input_combo_fullscreen_display")
        self.horizontalLayout_17.addWidget(self.input_combo_fullscreen_display)
        self.comboBox_3 = QtWidgets.QComboBox(self.groupbox_appearance)
        self.comboBox_3.setObjectName("comboBox_3")
        self.horizontalLayout_17.addWidget(self.comboBox_3)
        self.horizontalLayout_16.addLayout(self.horizontalLayout_17)
        self.verticalLayout_3.addLayout(self.horizontalLayout_16)
        self.gridLayout_2.addWidget(self.groupbox_appearance, 1, 0, 1, 1)
        self.groupbox_display_size = QtWidgets.QGroupBox(self.tab_display)
        self.groupbox_display_size.setObjectName("groupbox_display_size")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupbox_display_size)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.input_radiobutton_long_display = QtWidgets.QRadioButton(self.groupbox_display_size)
        self.input_radiobutton_long_display.setObjectName("input_radiobutton_long_display")
        self.horizontalLayout_5.addWidget(self.input_radiobutton_long_display)
        self.input_radiobutton_short_display = QtWidgets.QRadioButton(self.groupbox_display_size)
        self.input_radiobutton_short_display.setObjectName("input_radiobutton_short_display")
        self.horizontalLayout_5.addWidget(self.input_radiobutton_short_display)
        self.gridLayout_2.addWidget(self.groupbox_display_size, 0, 0, 1, 1)
        self.groupbox_detailed_summary_popup = QtWidgets.QGroupBox(self.tab_display)
        self.groupbox_detailed_summary_popup.setObjectName("groupbox_detailed_summary_popup")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupbox_detailed_summary_popup)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.input_checkbutton_show_tooltips = QtWidgets.QCheckBox(self.groupbox_detailed_summary_popup)
        self.input_checkbutton_show_tooltips.setObjectName("input_checkbutton_show_tooltips")
        self.gridLayout_3.addWidget(self.input_checkbutton_show_tooltips, 4, 0, 1, 1)
        self.input_radiobutton_popup_details_hover = QtWidgets.QRadioButton(self.groupbox_detailed_summary_popup)
        self.input_radiobutton_popup_details_hover.setObjectName("input_radiobutton_popup_details_hover")
        self.gridLayout_3.addWidget(self.input_radiobutton_popup_details_hover, 0, 0, 1, 1)
        self.input_radiobutton_popup_details_clicking = QtWidgets.QRadioButton(self.groupbox_detailed_summary_popup)
        self.input_radiobutton_popup_details_clicking.setObjectName("input_radiobutton_popup_details_clicking")
        self.gridLayout_3.addWidget(self.input_radiobutton_popup_details_clicking, 1, 0, 1, 1)
        self.input_checkbutton_show_grid = QtWidgets.QCheckBox(self.groupbox_detailed_summary_popup)
        self.input_checkbutton_show_grid.setObjectName("input_checkbutton_show_grid")
        self.gridLayout_3.addWidget(self.input_checkbutton_show_grid, 2, 0, 1, 1)
        self.input_radiobutton_close_details_hover = QtWidgets.QRadioButton(self.groupbox_detailed_summary_popup)
        self.input_radiobutton_close_details_hover.setObjectName("input_radiobutton_close_details_hover")
        self.gridLayout_3.addWidget(self.input_radiobutton_close_details_hover, 0, 1, 1, 1)
        self.input_radiobutton_close_details_clicking = QtWidgets.QRadioButton(self.groupbox_detailed_summary_popup)
        self.input_radiobutton_close_details_clicking.setObjectName("input_radiobutton_close_details_clicking")
        self.gridLayout_3.addWidget(self.input_radiobutton_close_details_clicking, 1, 1, 1, 1)
        self.input_checkbutton_highlight_new_events = QtWidgets.QCheckBox(self.groupbox_detailed_summary_popup)
        self.input_checkbutton_highlight_new_events.setObjectName("input_checkbutton_highlight_new_events")
        self.gridLayout_3.addWidget(self.input_checkbutton_highlight_new_events, 3, 0, 1, 1)
        self.input_combo_default_sort_field = QtWidgets.QComboBox(self.groupbox_detailed_summary_popup)
        self.input_combo_default_sort_field.setObjectName("input_combo_default_sort_field")
        self.gridLayout_3.addWidget(self.input_combo_default_sort_field, 5, 1, 1, 1)
        self.label_default_sort_field = QtWidgets.QLabel(self.groupbox_detailed_summary_popup)
        self.label_default_sort_field.setObjectName("label_default_sort_field")
        self.gridLayout_3.addWidget(self.label_default_sort_field, 5, 0, 1, 1)
        self.input_combo_default_sort_order = QtWidgets.QComboBox(self.groupbox_detailed_summary_popup)
        self.input_combo_default_sort_order.setObjectName("input_combo_default_sort_order")
        self.gridLayout_3.addWidget(self.input_combo_default_sort_order, 6, 1, 1, 1)
        self.label_default_sort_order = QtWidgets.QLabel(self.groupbox_detailed_summary_popup)
        self.label_default_sort_order.setObjectName("label_default_sort_order")
        self.gridLayout_3.addWidget(self.label_default_sort_order, 6, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupbox_detailed_summary_popup, 3, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 4, 0, 1, 1)
        self.tabs.addTab(self.tab_display, "")
        self.tab_filters = QtWidgets.QWidget()
        self.tab_filters.setObjectName("tab_filters")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_filters)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupbox_filters = QtWidgets.QGroupBox(self.tab_filters)
        self.groupbox_filters.setObjectName("groupbox_filters")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupbox_filters)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.input_checkbutton_re_status_information_enabled = QtWidgets.QCheckBox(self.groupbox_filters)
        self.input_checkbutton_re_status_information_enabled.setObjectName("input_checkbutton_re_status_information_enabled")
        self.gridLayout_5.addWidget(self.input_checkbutton_re_status_information_enabled, 17, 0, 1, 1)
        self.input_checkbutton_filter_all_unreachable_hosts = QtWidgets.QCheckBox(self.groupbox_filters)
        self.input_checkbutton_filter_all_unreachable_hosts.setObjectName("input_checkbutton_filter_all_unreachable_hosts")
        self.gridLayout_5.addWidget(self.input_checkbutton_filter_all_unreachable_hosts, 1, 0, 1, 1)
        self.input_checkbutton_filter_all_warning_services = QtWidgets.QCheckBox(self.groupbox_filters)
        self.input_checkbutton_filter_all_warning_services.setObjectName("input_checkbutton_filter_all_warning_services")
        self.gridLayout_5.addWidget(self.input_checkbutton_filter_all_warning_services, 5, 0, 1, 1)
        self.input_checkbutton_filter_all_critical_services = QtWidgets.QCheckBox(self.groupbox_filters)
        self.input_checkbutton_filter_all_critical_services.setObjectName("input_checkbutton_filter_all_critical_services")
        self.gridLayout_5.addWidget(self.input_checkbutton_filter_all_critical_services, 3, 0, 1, 1)
        self.input_checkbutton_filter_services_in_soft_state = QtWidgets.QCheckBox(self.groupbox_filters)
        self.input_checkbutton_filter_services_in_soft_state.setObjectName("input_checkbutton_filter_services_in_soft_state")
        self.gridLayout_5.addWidget(self.input_checkbutton_filter_services_in_soft_state, 10, 1, 1, 1)
        self.input_checkbutton_filter_hosts_services_maintenance = QtWidgets.QCheckBox(self.groupbox_filters)
        self.input_checkbutton_filter_hosts_services_maintenance.setObjectName("input_checkbutton_filter_hosts_services_maintenance")
        self.gridLayout_5.addWidget(self.input_checkbutton_filter_hosts_services_maintenance, 3, 1, 1, 1)
        self.input_checkbutton_filter_all_unknown_services = QtWidgets.QCheckBox(self.groupbox_filters)
        self.input_checkbutton_filter_all_unknown_services.setObjectName("input_checkbutton_filter_all_unknown_services")
        self.gridLayout_5.addWidget(self.input_checkbutton_filter_all_unknown_services, 4, 0, 1, 1)
        self.input_checkbutton_filter_all_flapping_hosts = QtWidgets.QCheckBox(self.groupbox_filters)
        self.input_checkbutton_filter_all_flapping_hosts.setObjectName("input_checkbutton_filter_all_flapping_hosts")
        self.gridLayout_5.addWidget(self.input_checkbutton_filter_all_flapping_hosts, 2, 0, 1, 1)
        self.label_python_re = QtWidgets.QLabel(self.groupbox_filters)
        self.label_python_re.setObjectName("label_python_re")
        self.gridLayout_5.addWidget(self.label_python_re, 20, 0, 1, 1)
        self.input_checkbutton_re_service_enabled = QtWidgets.QCheckBox(self.groupbox_filters)
        self.input_checkbutton_re_service_enabled.setObjectName("input_checkbutton_re_service_enabled")
        self.gridLayout_5.addWidget(self.input_checkbutton_re_service_enabled, 14, 0, 1, 1)
        self.input_checkbutton_filter_hosts_in_soft_state = QtWidgets.QCheckBox(self.groupbox_filters)
        self.input_checkbutton_filter_hosts_in_soft_state.setObjectName("input_checkbutton_filter_hosts_in_soft_state")
        self.gridLayout_5.addWidget(self.input_checkbutton_filter_hosts_in_soft_state, 9, 1, 1, 1)
        self.input_checkbutton_filter_services_on_unreachable_hosts = QtWidgets.QCheckBox(self.groupbox_filters)
        self.input_checkbutton_filter_services_on_unreachable_hosts.setObjectName("input_checkbutton_filter_services_on_unreachable_hosts")
        self.gridLayout_5.addWidget(self.input_checkbutton_filter_services_on_unreachable_hosts, 8, 1, 1, 1)
        self.input_checkbutton_filter_services_on_acknowledged_hosts = QtWidgets.QCheckBox(self.groupbox_filters)
        self.input_checkbutton_filter_services_on_acknowledged_hosts.setObjectName("input_checkbutton_filter_services_on_acknowledged_hosts")
        self.gridLayout_5.addWidget(self.input_checkbutton_filter_services_on_acknowledged_hosts, 4, 1, 1, 1)
        self.input_checkbutton_filter_services_on_down_hosts = QtWidgets.QCheckBox(self.groupbox_filters)
        self.input_checkbutton_filter_services_on_down_hosts.setObjectName("input_checkbutton_filter_services_on_down_hosts")
        self.gridLayout_5.addWidget(self.input_checkbutton_filter_services_on_down_hosts, 5, 1, 1, 1)
        self.input_checkbutton_filter_services_on_hosts_in_maintenance = QtWidgets.QCheckBox(self.groupbox_filters)
        self.input_checkbutton_filter_services_on_hosts_in_maintenance.setObjectName("input_checkbutton_filter_services_on_hosts_in_maintenance")
        self.gridLayout_5.addWidget(self.input_checkbutton_filter_services_on_hosts_in_maintenance, 6, 1, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.input_entry_re_host_pattern = QtWidgets.QLineEdit(self.groupbox_filters)
        self.input_entry_re_host_pattern.setObjectName("input_entry_re_host_pattern")
        self.horizontalLayout_8.addWidget(self.input_entry_re_host_pattern)
        self.input_checkbutton_re_host_reverse = QtWidgets.QCheckBox(self.groupbox_filters)
        self.input_checkbutton_re_host_reverse.setObjectName("input_checkbutton_re_host_reverse")
        self.horizontalLayout_8.addWidget(self.input_checkbutton_re_host_reverse)
        self.gridLayout_5.addLayout(self.horizontalLayout_8, 12, 0, 1, 2)
        self.input_checkbutton_filter_hosts_services_disabled_notifications = QtWidgets.QCheckBox(self.groupbox_filters)
        self.input_checkbutton_filter_hosts_services_disabled_notifications.setObjectName("input_checkbutton_filter_hosts_services_disabled_notifications")
        self.gridLayout_5.addWidget(self.input_checkbutton_filter_hosts_services_disabled_notifications, 1, 1, 1, 1)
        self.input_checkbutton_filter_acknowledged_hosts_services = QtWidgets.QCheckBox(self.groupbox_filters)
        self.input_checkbutton_filter_acknowledged_hosts_services.setObjectName("input_checkbutton_filter_acknowledged_hosts_services")
        self.gridLayout_5.addWidget(self.input_checkbutton_filter_acknowledged_hosts_services, 0, 1, 1, 1)
        self.input_checkbutton_filter_hosts_services_disabled_checks = QtWidgets.QCheckBox(self.groupbox_filters)
        self.input_checkbutton_filter_hosts_services_disabled_checks.setObjectName("input_checkbutton_filter_hosts_services_disabled_checks")
        self.gridLayout_5.addWidget(self.input_checkbutton_filter_hosts_services_disabled_checks, 2, 1, 1, 1)
        self.input_checkbutton_filter_all_flapping_services = QtWidgets.QCheckBox(self.groupbox_filters)
        self.input_checkbutton_filter_all_flapping_services.setObjectName("input_checkbutton_filter_all_flapping_services")
        self.gridLayout_5.addWidget(self.input_checkbutton_filter_all_flapping_services, 6, 0, 1, 1)
        self.input_checkbutton_filter_all_down_hosts = QtWidgets.QCheckBox(self.groupbox_filters)
        self.input_checkbutton_filter_all_down_hosts.setObjectName("input_checkbutton_filter_all_down_hosts")
        self.gridLayout_5.addWidget(self.input_checkbutton_filter_all_down_hosts, 0, 0, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.input_entry_re_service_pattern = QtWidgets.QLineEdit(self.groupbox_filters)
        self.input_entry_re_service_pattern.setObjectName("input_entry_re_service_pattern")
        self.horizontalLayout_9.addWidget(self.input_entry_re_service_pattern)
        self.input_checkbutton_re_service_reverse = QtWidgets.QCheckBox(self.groupbox_filters)
        self.input_checkbutton_re_service_reverse.setObjectName("input_checkbutton_re_service_reverse")
        self.horizontalLayout_9.addWidget(self.input_checkbutton_re_service_reverse)
        self.gridLayout_5.addLayout(self.horizontalLayout_9, 15, 0, 1, 2)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.input_entry_re_status_information_pattern = QtWidgets.QLineEdit(self.groupbox_filters)
        self.input_entry_re_status_information_pattern.setObjectName("input_entry_re_status_information_pattern")
        self.horizontalLayout_10.addWidget(self.input_entry_re_status_information_pattern)
        self.input_checkbutton_re_status_information_reverse = QtWidgets.QCheckBox(self.groupbox_filters)
        self.input_checkbutton_re_status_information_reverse.setObjectName("input_checkbutton_re_status_information_reverse")
        self.horizontalLayout_10.addWidget(self.input_checkbutton_re_status_information_reverse)
        self.gridLayout_5.addLayout(self.horizontalLayout_10, 18, 0, 1, 2)
        self.input_checkbutton_re_host_enabled = QtWidgets.QCheckBox(self.groupbox_filters)
        self.input_checkbutton_re_host_enabled.setObjectName("input_checkbutton_re_host_enabled")
        self.gridLayout_5.addWidget(self.input_checkbutton_re_host_enabled, 11, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupbox_filters, 0, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem4, 1, 0, 1, 1)
        self.tabs.addTab(self.tab_filters, "")
        self.tab_actions = QtWidgets.QWidget()
        self.tab_actions.setObjectName("tab_actions")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_actions)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.listview_actions = QtWidgets.QListView(self.tab_actions)
        self.listview_actions.setObjectName("listview_actions")
        self.gridLayout_6.addWidget(self.listview_actions, 0, 0, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.button_new_action = QtWidgets.QPushButton(self.tab_actions)
        self.button_new_action.setObjectName("button_new_action")
        self.verticalLayout_4.addWidget(self.button_new_action)
        self.button_edit_action = QtWidgets.QPushButton(self.tab_actions)
        self.button_edit_action.setObjectName("button_edit_action")
        self.verticalLayout_4.addWidget(self.button_edit_action)
        self.button_copy_action = QtWidgets.QPushButton(self.tab_actions)
        self.button_copy_action.setObjectName("button_copy_action")
        self.verticalLayout_4.addWidget(self.button_copy_action)
        self.button_delete_action = QtWidgets.QPushButton(self.tab_actions)
        self.button_delete_action.setObjectName("button_delete_action")
        self.verticalLayout_4.addWidget(self.button_delete_action)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem5)
        self.gridLayout_6.addLayout(self.verticalLayout_4, 0, 2, 1, 1)
        self.groupbox_connection_method = QtWidgets.QGroupBox(self.tab_actions)
        self.groupbox_connection_method.setObjectName("groupbox_connection_method")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupbox_connection_method)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.input_radiobutton_connect_by_host = QtWidgets.QRadioButton(self.groupbox_connection_method)
        self.input_radiobutton_connect_by_host.setObjectName("input_radiobutton_connect_by_host")
        self.verticalLayout_5.addWidget(self.input_radiobutton_connect_by_host)
        self.input_radiobutton_connect_by_dns = QtWidgets.QRadioButton(self.groupbox_connection_method)
        self.input_radiobutton_connect_by_dns.setObjectName("input_radiobutton_connect_by_dns")
        self.verticalLayout_5.addWidget(self.input_radiobutton_connect_by_dns)
        self.input_radiobutton_connect_by_ip = QtWidgets.QRadioButton(self.groupbox_connection_method)
        self.input_radiobutton_connect_by_ip.setObjectName("input_radiobutton_connect_by_ip")
        self.verticalLayout_5.addWidget(self.input_radiobutton_connect_by_ip)
        self.gridLayout_6.addWidget(self.groupbox_connection_method, 1, 0, 1, 1)
        self.tabs.addTab(self.tab_actions, "")
        self.tab_notifications = QtWidgets.QWidget()
        self.tab_notifications.setObjectName("tab_notifications")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_notifications)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.input_checkbutton_notification = QtWidgets.QCheckBox(self.tab_notifications)
        self.input_checkbutton_notification.setObjectName("input_checkbutton_notification")
        self.verticalLayout_6.addWidget(self.input_checkbutton_notification)
        self.groupbox_notifications = QtWidgets.QGroupBox(self.tab_notifications)
        self.groupbox_notifications.setObjectName("groupbox_notifications")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupbox_notifications)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_notifications = QtWidgets.QHBoxLayout()
        self.horizontalLayout_notifications.setObjectName("horizontalLayout_notifications")
        self.input_checkbutton_notify_if_warning = QtWidgets.QCheckBox(self.groupbox_notifications)
        self.input_checkbutton_notify_if_warning.setObjectName("input_checkbutton_notify_if_warning")
        self.horizontalLayout_notifications.addWidget(self.input_checkbutton_notify_if_warning)
        self.input_checkbutton_notify_if_critical = QtWidgets.QCheckBox(self.groupbox_notifications)
        self.input_checkbutton_notify_if_critical.setObjectName("input_checkbutton_notify_if_critical")
        self.horizontalLayout_notifications.addWidget(self.input_checkbutton_notify_if_critical)
        self.input_checkbutton_notify_if_unknown = QtWidgets.QCheckBox(self.groupbox_notifications)
        self.input_checkbutton_notify_if_unknown.setObjectName("input_checkbutton_notify_if_unknown")
        self.horizontalLayout_notifications.addWidget(self.input_checkbutton_notify_if_unknown)
        self.input_checkbutton_notify_if_unreachable = QtWidgets.QCheckBox(self.groupbox_notifications)
        self.input_checkbutton_notify_if_unreachable.setObjectName("input_checkbutton_notify_if_unreachable")
        self.horizontalLayout_notifications.addWidget(self.input_checkbutton_notify_if_unreachable)
        self.input_checkbutton_notify_if_down = QtWidgets.QCheckBox(self.groupbox_notifications)
        self.input_checkbutton_notify_if_down.setObjectName("input_checkbutton_notify_if_down")
        self.horizontalLayout_notifications.addWidget(self.input_checkbutton_notify_if_down)
        self.verticalLayout_7.addLayout(self.horizontalLayout_notifications)
        self.input_checkbutton_notification_flashing = QtWidgets.QCheckBox(self.groupbox_notifications)
        self.input_checkbutton_notification_flashing.setObjectName("input_checkbutton_notification_flashing")
        self.verticalLayout_7.addWidget(self.input_checkbutton_notification_flashing)
        self.input_checkbutton_notification_desktop = QtWidgets.QCheckBox(self.groupbox_notifications)
        self.input_checkbutton_notification_desktop.setObjectName("input_checkbutton_notification_desktop")
        self.verticalLayout_7.addWidget(self.input_checkbutton_notification_desktop)
        self.input_checkbutton_notification_sound = QtWidgets.QCheckBox(self.groupbox_notifications)
        self.input_checkbutton_notification_sound.setObjectName("input_checkbutton_notification_sound")
        self.verticalLayout_7.addWidget(self.input_checkbutton_notification_sound)
        self.input_checkbutton_notification_sound_repeat = QtWidgets.QCheckBox(self.groupbox_notifications)
        self.input_checkbutton_notification_sound_repeat.setObjectName("input_checkbutton_notification_sound_repeat")
        self.verticalLayout_7.addWidget(self.input_checkbutton_notification_sound_repeat)
        self.input_radiobutton_notification_default_sound = QtWidgets.QRadioButton(self.groupbox_notifications)
        self.input_radiobutton_notification_default_sound.setObjectName("input_radiobutton_notification_default_sound")
        self.verticalLayout_7.addWidget(self.input_radiobutton_notification_default_sound)
        self.input_radiobutton_notification_custom_sound = QtWidgets.QRadioButton(self.groupbox_notifications)
        self.input_radiobutton_notification_custom_sound.setObjectName("input_radiobutton_notification_custom_sound")
        self.verticalLayout_7.addWidget(self.input_radiobutton_notification_custom_sound)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_notification_sound_options_custom_sounds_warning = QtWidgets.QLabel(self.groupbox_notifications)
        self.label_notification_sound_options_custom_sounds_warning.setObjectName("label_notification_sound_options_custom_sounds_warning")
        self.gridLayout_7.addWidget(self.label_notification_sound_options_custom_sounds_warning, 0, 0, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.groupbox_notifications)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_7.addWidget(self.pushButton_7, 1, 1, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.groupbox_notifications)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_7.addWidget(self.pushButton_8, 1, 2, 1, 1)
        self.label_notification_sound_options_custom_sounds_critical = QtWidgets.QLabel(self.groupbox_notifications)
        self.label_notification_sound_options_custom_sounds_critical.setObjectName("label_notification_sound_options_custom_sounds_critical")
        self.gridLayout_7.addWidget(self.label_notification_sound_options_custom_sounds_critical, 1, 0, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.groupbox_notifications)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_7.addWidget(self.pushButton_5, 0, 1, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.groupbox_notifications)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_7.addWidget(self.pushButton_6, 0, 2, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.groupbox_notifications)
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout_7.addWidget(self.pushButton_9, 2, 1, 1, 1)
        self.label_notification_sound_options_custom_sounds_down = QtWidgets.QLabel(self.groupbox_notifications)
        self.label_notification_sound_options_custom_sounds_down.setObjectName("label_notification_sound_options_custom_sounds_down")
        self.gridLayout_7.addWidget(self.label_notification_sound_options_custom_sounds_down, 2, 0, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(self.groupbox_notifications)
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout_7.addWidget(self.pushButton_10, 2, 2, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout_7)
        self.checkBox_37 = QtWidgets.QCheckBox(self.groupbox_notifications)
        self.checkBox_37.setObjectName("checkBox_37")
        self.verticalLayout_7.addWidget(self.checkBox_37)
        self.verticalLayout_6.addWidget(self.groupbox_notifications)
        self.tabs.addTab(self.tab_notifications, "")
        self.tab_colors = QtWidgets.QWidget()
        self.tab_colors.setObjectName("tab_colors")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.tab_colors)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.pushButton_12 = QtWidgets.QPushButton(self.tab_colors)
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout_12.addWidget(self.pushButton_12, 2, 2, 1, 1)
        self.label_color_unknown = QtWidgets.QLabel(self.tab_colors)
        self.label_color_unknown.setObjectName("label_color_unknown")
        self.gridLayout_12.addWidget(self.label_color_unknown, 5, 0, 1, 1)
        self.label_color_critical = QtWidgets.QLabel(self.tab_colors)
        self.label_color_critical.setObjectName("label_color_critical")
        self.gridLayout_12.addWidget(self.label_color_critical, 4, 0, 1, 1)
        self.pushButton_20 = QtWidgets.QPushButton(self.tab_colors)
        self.pushButton_20.setObjectName("pushButton_20")
        self.gridLayout_12.addWidget(self.pushButton_20, 6, 2, 1, 1)
        self.pushButton_18 = QtWidgets.QPushButton(self.tab_colors)
        self.pushButton_18.setObjectName("pushButton_18")
        self.gridLayout_12.addWidget(self.pushButton_18, 5, 2, 1, 1)
        self.pushButton_23 = QtWidgets.QPushButton(self.tab_colors)
        self.pushButton_23.setObjectName("pushButton_23")
        self.gridLayout_12.addWidget(self.pushButton_23, 8, 1, 1, 1)
        self.pushButton_17 = QtWidgets.QPushButton(self.tab_colors)
        self.pushButton_17.setObjectName("pushButton_17")
        self.gridLayout_12.addWidget(self.pushButton_17, 5, 1, 1, 1)
        self.label_table_background = QtWidgets.QLabel(self.tab_colors)
        self.label_table_background.setObjectName("label_table_background")
        self.gridLayout_12.addWidget(self.label_table_background, 1, 2, 1, 1)
        self.label_table_text = QtWidgets.QLabel(self.tab_colors)
        self.label_table_text.setObjectName("label_table_text")
        self.gridLayout_12.addWidget(self.label_table_text, 1, 1, 1, 1)
        self.pushButton_14 = QtWidgets.QPushButton(self.tab_colors)
        self.pushButton_14.setObjectName("pushButton_14")
        self.gridLayout_12.addWidget(self.pushButton_14, 3, 2, 1, 1)
        self.label_color_warning = QtWidgets.QLabel(self.tab_colors)
        self.label_color_warning.setObjectName("label_color_warning")
        self.gridLayout_12.addWidget(self.label_color_warning, 3, 0, 1, 1)
        self.pushButton_22 = QtWidgets.QPushButton(self.tab_colors)
        self.pushButton_22.setObjectName("pushButton_22")
        self.gridLayout_12.addWidget(self.pushButton_22, 7, 2, 1, 1)
        self.label_color_error = QtWidgets.QLabel(self.tab_colors)
        self.label_color_error.setObjectName("label_color_error")
        self.gridLayout_12.addWidget(self.label_color_error, 8, 0, 1, 1)
        self.pushButton_16 = QtWidgets.QPushButton(self.tab_colors)
        self.pushButton_16.setObjectName("pushButton_16")
        self.gridLayout_12.addWidget(self.pushButton_16, 4, 2, 1, 1)
        self.pushButton_11 = QtWidgets.QPushButton(self.tab_colors)
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout_12.addWidget(self.pushButton_11, 2, 1, 1, 1)
        self.label_color_unreachable = QtWidgets.QLabel(self.tab_colors)
        self.label_color_unreachable.setObjectName("label_color_unreachable")
        self.gridLayout_12.addWidget(self.label_color_unreachable, 6, 0, 1, 1)
        self.label_color_down = QtWidgets.QLabel(self.tab_colors)
        self.label_color_down.setObjectName("label_color_down")
        self.gridLayout_12.addWidget(self.label_color_down, 7, 0, 1, 1)
        self.label_color_ok = QtWidgets.QLabel(self.tab_colors)
        self.label_color_ok.setObjectName("label_color_ok")
        self.gridLayout_12.addWidget(self.label_color_ok, 2, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_12.addItem(spacerItem6, 10, 1, 1, 1)
        self.pushButton_21 = QtWidgets.QPushButton(self.tab_colors)
        self.pushButton_21.setObjectName("pushButton_21")
        self.gridLayout_12.addWidget(self.pushButton_21, 7, 1, 1, 1)
        self.pushButton_13 = QtWidgets.QPushButton(self.tab_colors)
        self.pushButton_13.setObjectName("pushButton_13")
        self.gridLayout_12.addWidget(self.pushButton_13, 3, 1, 1, 1)
        self.pushButton_19 = QtWidgets.QPushButton(self.tab_colors)
        self.pushButton_19.setObjectName("pushButton_19")
        self.gridLayout_12.addWidget(self.pushButton_19, 6, 1, 1, 1)
        self.pushButton_24 = QtWidgets.QPushButton(self.tab_colors)
        self.pushButton_24.setObjectName("pushButton_24")
        self.gridLayout_12.addWidget(self.pushButton_24, 8, 2, 1, 1)
        self.pushButton_15 = QtWidgets.QPushButton(self.tab_colors)
        self.pushButton_15.setObjectName("pushButton_15")
        self.gridLayout_12.addWidget(self.pushButton_15, 4, 1, 1, 1)
        self.label_colors = QtWidgets.QLabel(self.tab_colors)
        self.label_colors.setObjectName("label_colors")
        self.gridLayout_12.addWidget(self.label_colors, 0, 0, 1, 3)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.button_colors_reset = QtWidgets.QPushButton(self.tab_colors)
        self.button_colors_reset.setObjectName("button_colors_reset")
        self.horizontalLayout_12.addWidget(self.button_colors_reset)
        self.button_colors_defaults = QtWidgets.QPushButton(self.tab_colors)
        self.button_colors_defaults.setObjectName("button_colors_defaults")
        self.horizontalLayout_12.addWidget(self.button_colors_defaults)
        self.gridLayout_12.addLayout(self.horizontalLayout_12, 9, 0, 1, 3)
        self.tabs.addTab(self.tab_colors, "")
        self.tab_defaults = QtWidgets.QWidget()
        self.tab_defaults.setObjectName("tab_defaults")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.tab_defaults)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_defaults = QtWidgets.QLabel(self.tab_defaults)
        self.label_defaults.setObjectName("label_defaults")
        self.verticalLayout_9.addWidget(self.label_defaults)
        self.label_defaults_acknowledge = QtWidgets.QGroupBox(self.tab_defaults)
        self.label_defaults_acknowledge.setObjectName("label_defaults_acknowledge")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.label_defaults_acknowledge)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.input_checkbutton_defaults_acknowledge_sticky = QtWidgets.QCheckBox(self.label_defaults_acknowledge)
        self.input_checkbutton_defaults_acknowledge_sticky.setObjectName("input_checkbutton_defaults_acknowledge_sticky")
        self.verticalLayout_10.addWidget(self.input_checkbutton_defaults_acknowledge_sticky)
        self.input_checkbutton_defaults_acknowledge_send_notification = QtWidgets.QCheckBox(self.label_defaults_acknowledge)
        self.input_checkbutton_defaults_acknowledge_send_notification.setObjectName("input_checkbutton_defaults_acknowledge_send_notification")
        self.verticalLayout_10.addWidget(self.input_checkbutton_defaults_acknowledge_send_notification)
        self.input_checkbutton_defaults_acknowledge_persistent_comment = QtWidgets.QCheckBox(self.label_defaults_acknowledge)
        self.input_checkbutton_defaults_acknowledge_persistent_comment.setObjectName("input_checkbutton_defaults_acknowledge_persistent_comment")
        self.verticalLayout_10.addWidget(self.input_checkbutton_defaults_acknowledge_persistent_comment)
        self.input_checkbutton_defaults_acknowledge_all_services = QtWidgets.QCheckBox(self.label_defaults_acknowledge)
        self.input_checkbutton_defaults_acknowledge_all_services.setObjectName("input_checkbutton_defaults_acknowledge_all_services")
        self.verticalLayout_10.addWidget(self.input_checkbutton_defaults_acknowledge_all_services)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_defaults_acknowledge_comment = QtWidgets.QLabel(self.label_defaults_acknowledge)
        self.label_defaults_acknowledge_comment.setObjectName("label_defaults_acknowledge_comment")
        self.horizontalLayout_13.addWidget(self.label_defaults_acknowledge_comment)
        self.input_entry_defaults_acknowledge_comment = QtWidgets.QLineEdit(self.label_defaults_acknowledge)
        self.input_entry_defaults_acknowledge_comment.setObjectName("input_entry_defaults_acknowledge_comment")
        self.horizontalLayout_13.addWidget(self.input_entry_defaults_acknowledge_comment)
        self.verticalLayout_10.addLayout(self.horizontalLayout_13)
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.input_radiobutton_defaults_downtime_type_flexible = QtWidgets.QRadioButton(self.label_defaults_acknowledge)
        self.input_radiobutton_defaults_downtime_type_flexible.setObjectName("input_radiobutton_defaults_downtime_type_flexible")
        self.gridLayout_9.addWidget(self.input_radiobutton_defaults_downtime_type_flexible, 1, 1, 1, 1)
        self.input_radiobutton_defaults_downtime_type_fixed = QtWidgets.QRadioButton(self.label_defaults_acknowledge)
        self.input_radiobutton_defaults_downtime_type_fixed.setObjectName("input_radiobutton_defaults_downtime_type_fixed")
        self.gridLayout_9.addWidget(self.input_radiobutton_defaults_downtime_type_fixed, 0, 1, 1, 1)
        self.label_defaults_downtime_type = QtWidgets.QLabel(self.label_defaults_acknowledge)
        self.label_defaults_downtime_type.setObjectName("label_defaults_downtime_type")
        self.gridLayout_9.addWidget(self.label_defaults_downtime_type, 0, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem7, 0, 2, 1, 1)
        self.verticalLayout_10.addLayout(self.gridLayout_9)
        self.verticalLayout_9.addWidget(self.label_defaults_acknowledge)
        self.label_defaults_downtime = QtWidgets.QGroupBox(self.tab_defaults)
        self.label_defaults_downtime.setObjectName("label_defaults_downtime")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.label_defaults_downtime)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_defaults_downtime_comment = QtWidgets.QLabel(self.label_defaults_downtime)
        self.label_defaults_downtime_comment.setObjectName("label_defaults_downtime_comment")
        self.gridLayout_10.addWidget(self.label_defaults_downtime_comment, 1, 0, 1, 1)
        self.label_defaults_duration_comment = QtWidgets.QLabel(self.label_defaults_downtime)
        self.label_defaults_duration_comment.setObjectName("label_defaults_duration_comment")
        self.gridLayout_10.addWidget(self.label_defaults_duration_comment, 0, 0, 1, 1)
        self.input_spinbutton_defaults_downtime_duration_minutes = QtWidgets.QSpinBox(self.label_defaults_downtime)
        self.input_spinbutton_defaults_downtime_duration_minutes.setObjectName("input_spinbutton_defaults_downtime_duration_minutes")
        self.gridLayout_10.addWidget(self.input_spinbutton_defaults_downtime_duration_minutes, 0, 3, 1, 1)
        self.input_spinbutton_defaults_downtime_duration_hours = QtWidgets.QSpinBox(self.label_defaults_downtime)
        self.input_spinbutton_defaults_downtime_duration_hours.setObjectName("input_spinbutton_defaults_downtime_duration_hours")
        self.gridLayout_10.addWidget(self.input_spinbutton_defaults_downtime_duration_hours, 0, 1, 1, 1)
        self.label_duration_hour = QtWidgets.QLabel(self.label_defaults_downtime)
        self.label_duration_hour.setObjectName("label_duration_hour")
        self.gridLayout_10.addWidget(self.label_duration_hour, 0, 2, 1, 1)
        self.label_duration_minutes = QtWidgets.QLabel(self.label_defaults_downtime)
        self.label_duration_minutes.setObjectName("label_duration_minutes")
        self.gridLayout_10.addWidget(self.label_duration_minutes, 0, 4, 1, 1)
        self.input_entry_defaults_downtime_comment = QtWidgets.QLineEdit(self.label_defaults_downtime)
        self.input_entry_defaults_downtime_comment.setObjectName("input_entry_defaults_downtime_comment")
        self.gridLayout_10.addWidget(self.input_entry_defaults_downtime_comment, 1, 1, 1, 4)
        self.verticalLayout_9.addWidget(self.label_defaults_downtime)
        self.label_acknowledge_submit_result = QtWidgets.QGroupBox(self.tab_defaults)
        self.label_acknowledge_submit_result.setObjectName("label_acknowledge_submit_result")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.label_acknowledge_submit_result)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.input_entry_defaults_submit_check_result_comment = QtWidgets.QLabel(self.label_acknowledge_submit_result)
        self.input_entry_defaults_submit_check_result_comment.setObjectName("input_entry_defaults_submit_check_result_comment")
        self.horizontalLayout_14.addWidget(self.input_entry_defaults_submit_check_result_comment)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.label_acknowledge_submit_result)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.horizontalLayout_14.addWidget(self.lineEdit_6)
        self.verticalLayout_9.addWidget(self.label_acknowledge_submit_result)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem8)
        self.tabs.addTab(self.tab_defaults, "")
        self.verticalLayout.addWidget(self.tabs)
        self.button_box = QtWidgets.QDialogButtonBox(settings_dialog)
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.verticalLayout.addWidget(self.button_box)

        self.retranslateUi(settings_dialog)
        self.tabs.setCurrentIndex(6)
        self.button_box.accepted.connect(settings_dialog.accept)
        self.button_box.rejected.connect(settings_dialog.reject)
        self.input_checkbutton_debug_mode.toggled['bool'].connect(self.input_checkbutton_debug_to_file.setVisible)
        self.input_checkbutton_debug_mode.toggled['bool'].connect(self.input_entry_debug_file.setVisible)
        self.input_checkbutton_debug_to_file.toggled['bool'].connect(self.input_entry_debug_file.setVisible)
        QtCore.QMetaObject.connectSlotsByName(settings_dialog)

    def retranslateUi(self, settings_dialog):
        _translate = QtCore.QCoreApplication.translate
        settings_dialog.setWindowTitle(_translate("settings_dialog", "Nagstamon 1.1 settings"))
        self.input_checkbutton_debug_mode.setText(_translate("settings_dialog", "Debug mode"))
        self.input_checkbutton_debug_to_file.setText(_translate("settings_dialog", "Debug to file:"))
        self.button_new_server.setText(_translate("settings_dialog", "New server..."))
        self.button_edit_server.setText(_translate("settings_dialog", "Edit server..."))
        self.button_copy_server.setText(_translate("settings_dialog", "Copy server..."))
        self.button_delete_server.setText(_translate("settings_dialog", "Delete server"))
        self.input_checkbutton_use_system_keyring.setText(_translate("settings_dialog", "Use system keyring for server credentials"))
        self.label_update_interval_seconds.setText(_translate("settings_dialog", "Update interval in seconds:"))
        self.input_checkbutton_check_for_new_version.setText(_translate("settings_dialog", "Check for new version at startup"))
        self.button_check_for_new_version_now.setText(_translate("settings_dialog", "Check for new version now"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_servers), _translate("settings_dialog", "Servers"))
        self.groupbox_appearance.setTitle(_translate("settings_dialog", "Appearance:"))
        self.input_radiobutton_statusbar_floating.setText(_translate("settings_dialog", "Floating statusbar"))
        self.input_radiobutton_appindicator.setText(_translate("settings_dialog", "AppIndicator (Ubuntu & friends)"))
        self.input_radiobutton_icon_in_systray.setText(_translate("settings_dialog", "Icon in systray"))
        self.label_systray_popup_offset.setText(_translate("settings_dialog", "Systray-popup-offset:"))
        self.input_radiobutton_fullscreen.setText(_translate("settings_dialog", "Fullscreen"))
        self.input_combo_fullscreen_display.setText(_translate("settings_dialog", "Display to use:"))
        self.groupbox_display_size.setTitle(_translate("settings_dialog", "Statusbar display size"))
        self.input_radiobutton_long_display.setText(_translate("settings_dialog", "Long  (\"1 WARNING 4 CRITICAL\")"))
        self.input_radiobutton_short_display.setText(_translate("settings_dialog", "Short  (\"1 4\")"))
        self.groupbox_detailed_summary_popup.setTitle(_translate("settings_dialog", "Statusbar details popup:"))
        self.input_checkbutton_show_tooltips.setText(_translate("settings_dialog", "Show tooltips in status details overview"))
        self.input_radiobutton_popup_details_hover.setText(_translate("settings_dialog", "Popup when hovering over statusbar"))
        self.input_radiobutton_popup_details_clicking.setText(_translate("settings_dialog", "Popup when clicking statusbar"))
        self.input_checkbutton_show_grid.setText(_translate("settings_dialog", "Show grid in status details overview"))
        self.input_radiobutton_close_details_hover.setText(_translate("settings_dialog", "Close when hovering out of popup"))
        self.input_radiobutton_close_details_clicking.setText(_translate("settings_dialog", "Close when clicking statusbar"))
        self.input_checkbutton_highlight_new_events.setText(_translate("settings_dialog", "Highlight new events in status details overview"))
        self.label_default_sort_field.setText(_translate("settings_dialog", "Default sort field:"))
        self.label_default_sort_order.setText(_translate("settings_dialog", "Default sort order:"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_display), _translate("settings_dialog", "Display"))
        self.groupbox_filters.setTitle(_translate("settings_dialog", "Filter out the following:"))
        self.input_checkbutton_re_status_information_enabled.setText(_translate("settings_dialog", "CheckBox"))
        self.input_checkbutton_filter_all_unreachable_hosts.setText(_translate("settings_dialog", "All unreachable hosts"))
        self.input_checkbutton_filter_all_warning_services.setText(_translate("settings_dialog", "All warning services"))
        self.input_checkbutton_filter_all_critical_services.setText(_translate("settings_dialog", "All critical services"))
        self.input_checkbutton_filter_services_in_soft_state.setText(_translate("settings_dialog", "Services in soft state"))
        self.input_checkbutton_filter_hosts_services_maintenance.setText(_translate("settings_dialog", "Hosts & services down for maintenance"))
        self.input_checkbutton_filter_all_unknown_services.setText(_translate("settings_dialog", "All unknown services"))
        self.input_checkbutton_filter_all_flapping_hosts.setText(_translate("settings_dialog", "All flapping hosts"))
        self.label_python_re.setText(_translate("settings_dialog", "See Python Regular Expressions HOWTO for filtering details"))
        self.input_checkbutton_re_service_enabled.setText(_translate("settings_dialog", "Regular expression for services"))
        self.input_checkbutton_filter_hosts_in_soft_state.setText(_translate("settings_dialog", "Hosts in soft state"))
        self.input_checkbutton_filter_services_on_unreachable_hosts.setText(_translate("settings_dialog", "Services on unreachable hosts"))
        self.input_checkbutton_filter_services_on_acknowledged_hosts.setText(_translate("settings_dialog", "Services on acknowledged hosts"))
        self.input_checkbutton_filter_services_on_down_hosts.setText(_translate("settings_dialog", "Services on down hosts"))
        self.input_checkbutton_filter_services_on_hosts_in_maintenance.setText(_translate("settings_dialog", "Services on hosts in maintenance"))
        self.input_checkbutton_re_host_reverse.setText(_translate("settings_dialog", "reverse"))
        self.input_checkbutton_filter_hosts_services_disabled_notifications.setText(_translate("settings_dialog", "Hosts & services with disabled notifications"))
        self.input_checkbutton_filter_acknowledged_hosts_services.setText(_translate("settings_dialog", "Acknowledged hosts & services"))
        self.input_checkbutton_filter_hosts_services_disabled_checks.setText(_translate("settings_dialog", "Hosts & services with disabled checks"))
        self.input_checkbutton_filter_all_flapping_services.setText(_translate("settings_dialog", "All flapping services"))
        self.input_checkbutton_filter_all_down_hosts.setText(_translate("settings_dialog", "All down hosts"))
        self.input_checkbutton_re_service_reverse.setText(_translate("settings_dialog", "reverse"))
        self.input_checkbutton_re_status_information_reverse.setText(_translate("settings_dialog", "reverse"))
        self.input_checkbutton_re_host_enabled.setText(_translate("settings_dialog", "Regular expression for hosts"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_filters), _translate("settings_dialog", "Filters"))
        self.button_new_action.setText(_translate("settings_dialog", "New action..."))
        self.button_edit_action.setText(_translate("settings_dialog", "Edit action..."))
        self.button_copy_action.setText(_translate("settings_dialog", "Copy action..."))
        self.button_delete_action.setText(_translate("settings_dialog", "Delete action"))
        self.groupbox_connection_method.setTitle(_translate("settings_dialog", "Connection method:"))
        self.input_radiobutton_connect_by_host.setText(_translate("settings_dialog", "Hostname"))
        self.input_radiobutton_connect_by_dns.setText(_translate("settings_dialog", "DNS name"))
        self.input_radiobutton_connect_by_ip.setText(_translate("settings_dialog", "IP"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_actions), _translate("settings_dialog", "Actions"))
        self.input_checkbutton_notification.setText(_translate("settings_dialog", "Enable notification"))
        self.groupbox_notifications.setTitle(_translate("settings_dialog", "Notifications:"))
        self.input_checkbutton_notify_if_warning.setText(_translate("settings_dialog", "WARNING"))
        self.input_checkbutton_notify_if_critical.setText(_translate("settings_dialog", "CRITICAL"))
        self.input_checkbutton_notify_if_unknown.setText(_translate("settings_dialog", "UNKNOWN"))
        self.input_checkbutton_notify_if_unreachable.setText(_translate("settings_dialog", "UNREACHABLE"))
        self.input_checkbutton_notify_if_down.setText(_translate("settings_dialog", "DOWN"))
        self.input_checkbutton_notification_flashing.setText(_translate("settings_dialog", "Flashing statusbar/appindicator/systray icon"))
        self.input_checkbutton_notification_desktop.setText(_translate("settings_dialog", "Desktop notification"))
        self.input_checkbutton_notification_sound.setText(_translate("settings_dialog", "Enable sound"))
        self.input_checkbutton_notification_sound_repeat.setText(_translate("settings_dialog", "Repeat sound until notification has been noticed"))
        self.input_radiobutton_notification_default_sound.setText(_translate("settings_dialog", "Use default Nagios sounds"))
        self.input_radiobutton_notification_custom_sound.setText(_translate("settings_dialog", "Use custom sounds"))
        self.label_notification_sound_options_custom_sounds_warning.setText(_translate("settings_dialog", "WARNING:"))
        self.pushButton_7.setText(_translate("settings_dialog", "PushButton"))
        self.pushButton_8.setText(_translate("settings_dialog", "PushButton"))
        self.label_notification_sound_options_custom_sounds_critical.setText(_translate("settings_dialog", "CRITICAL:"))
        self.pushButton_5.setText(_translate("settings_dialog", "PushButton"))
        self.pushButton_6.setText(_translate("settings_dialog", "PushButton"))
        self.pushButton_9.setText(_translate("settings_dialog", "PushButton"))
        self.label_notification_sound_options_custom_sounds_down.setText(_translate("settings_dialog", "DOWN:"))
        self.pushButton_10.setText(_translate("settings_dialog", "PushButton"))
        self.checkBox_37.setText(_translate("settings_dialog", "CheckBox"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_notifications), _translate("settings_dialog", "Notifications"))
        self.pushButton_12.setText(_translate("settings_dialog", "PushButton"))
        self.label_color_unknown.setText(_translate("settings_dialog", " UNKNOWN: "))
        self.label_color_critical.setText(_translate("settings_dialog", " CRITICAL: "))
        self.pushButton_20.setText(_translate("settings_dialog", "PushButton"))
        self.pushButton_18.setText(_translate("settings_dialog", "PushButton"))
        self.pushButton_23.setText(_translate("settings_dialog", "PushButton"))
        self.pushButton_17.setText(_translate("settings_dialog", "PushButton"))
        self.label_table_background.setText(_translate("settings_dialog", "Background:"))
        self.label_table_text.setText(_translate("settings_dialog", "Text:"))
        self.pushButton_14.setText(_translate("settings_dialog", "PushButton"))
        self.label_color_warning.setText(_translate("settings_dialog", " WARNING: "))
        self.pushButton_22.setText(_translate("settings_dialog", "PushButton"))
        self.label_color_error.setText(_translate("settings_dialog", "ERROR:"))
        self.pushButton_16.setText(_translate("settings_dialog", "PushButton"))
        self.pushButton_11.setText(_translate("settings_dialog", "PushButton"))
        self.label_color_unreachable.setText(_translate("settings_dialog", " UNREACHABLE: "))
        self.label_color_down.setText(_translate("settings_dialog", " DOWN: "))
        self.label_color_ok.setText(_translate("settings_dialog", " OK: "))
        self.pushButton_21.setText(_translate("settings_dialog", "PushButton"))
        self.pushButton_13.setText(_translate("settings_dialog", "PushButton"))
        self.pushButton_19.setText(_translate("settings_dialog", "PushButton"))
        self.pushButton_24.setText(_translate("settings_dialog", "PushButton"))
        self.pushButton_15.setText(_translate("settings_dialog", "PushButton"))
        self.label_colors.setText(_translate("settings_dialog", "Set colors for text and background of status information:"))
        self.button_colors_reset.setText(_translate("settings_dialog", "Reset to previous"))
        self.button_colors_defaults.setText(_translate("settings_dialog", "Defaults"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_colors), _translate("settings_dialog", "Colors"))
        self.label_defaults.setText(_translate("settings_dialog", "Set some default settings for default actions:"))
        self.label_defaults_acknowledge.setTitle(_translate("settings_dialog", "Acknowledgements:"))
        self.input_checkbutton_defaults_acknowledge_sticky.setText(_translate("settings_dialog", "Sticky acknowledgement"))
        self.input_checkbutton_defaults_acknowledge_send_notification.setText(_translate("settings_dialog", "Send notification"))
        self.input_checkbutton_defaults_acknowledge_persistent_comment.setText(_translate("settings_dialog", "Persistent comment"))
        self.input_checkbutton_defaults_acknowledge_all_services.setText(_translate("settings_dialog", "Acknowledge all services on host"))
        self.label_defaults_acknowledge_comment.setText(_translate("settings_dialog", "Comment:"))
        self.input_radiobutton_defaults_downtime_type_flexible.setText(_translate("settings_dialog", "Flexible"))
        self.input_radiobutton_defaults_downtime_type_fixed.setText(_translate("settings_dialog", "Fixed"))
        self.label_defaults_downtime_type.setText(_translate("settings_dialog", "Type:"))
        self.label_defaults_downtime.setTitle(_translate("settings_dialog", "Downtime:"))
        self.label_defaults_downtime_comment.setText(_translate("settings_dialog", "Comment:"))
        self.label_defaults_duration_comment.setText(_translate("settings_dialog", "Duration:"))
        self.label_duration_hour.setText(_translate("settings_dialog", "hours"))
        self.label_duration_minutes.setText(_translate("settings_dialog", "minutes"))
        self.label_acknowledge_submit_result.setTitle(_translate("settings_dialog", "Submit check result:"))
        self.input_entry_defaults_submit_check_result_comment.setText(_translate("settings_dialog", "Comment:"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_defaults), _translate("settings_dialog", "Defaults"))

