# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings_action.ui'
#
# Created: Mon Mar 23 14:59:45 2015
#      by: PyQt5 UI code generator 5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_settings_action_dialog(object):
    def setupUi(self, settings_action_dialog):
        settings_action_dialog.setObjectName("settings_action_dialog")
        settings_action_dialog.resize(561, 717)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(settings_action_dialog.sizePolicy().hasHeightForWidth())
        settings_action_dialog.setSizePolicy(sizePolicy)
        self.gridLayout = QtWidgets.QGridLayout(settings_action_dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_6 = QtWidgets.QLineEdit(settings_action_dialog)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout.addWidget(self.lineEdit_6, 18, 0, 1, 7)
        self.radioButton = QtWidgets.QRadioButton(settings_action_dialog)
        self.radioButton.setObjectName("radioButton")
        self.gridLayout.addWidget(self.radioButton, 23, 0, 1, 7)
        self.label_4 = QtWidgets.QLabel(settings_action_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.checkBox_4 = QtWidgets.QCheckBox(settings_action_dialog)
        self.checkBox_4.setObjectName("checkBox_4")
        self.gridLayout.addWidget(self.checkBox_4, 13, 0, 1, 1)
        self.checkBox_6 = QtWidgets.QCheckBox(settings_action_dialog)
        self.checkBox_6.setObjectName("checkBox_6")
        self.gridLayout.addWidget(self.checkBox_6, 17, 0, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(settings_action_dialog)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout.addWidget(self.lineEdit_4, 14, 0, 1, 7)
        self.radioButton_2 = QtWidgets.QRadioButton(settings_action_dialog)
        self.radioButton_2.setObjectName("radioButton_2")
        self.gridLayout.addWidget(self.radioButton_2, 24, 0, 1, 7)
        self.label_6 = QtWidgets.QLabel(settings_action_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 6, 0, 1, 1)
        self.label = QtWidgets.QLabel(settings_action_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(settings_action_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(settings_action_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 7, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(settings_action_dialog)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 21, 0, 1, 7)
        self.label_11 = QtWidgets.QLabel(settings_action_dialog)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 19, 0, 1, 7)
        self.checkBox = QtWidgets.QCheckBox(settings_action_dialog)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox, 0, 0, 1, 7)
        self.label_3 = QtWidgets.QLabel(settings_action_dialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 2, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(settings_action_dialog)
        self.comboBox_2.setObjectName("comboBox_2")
        self.gridLayout.addWidget(self.comboBox_2, 4, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(settings_action_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 10, 0, 1, 1)
        self.checkBox_5 = QtWidgets.QCheckBox(settings_action_dialog)
        self.checkBox_5.setObjectName("checkBox_5")
        self.gridLayout.addWidget(self.checkBox_5, 15, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(settings_action_dialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 2, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(settings_action_dialog)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout.addWidget(self.lineEdit_5, 16, 0, 1, 7)
        self.comboBox = QtWidgets.QComboBox(settings_action_dialog)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout.addWidget(self.comboBox, 1, 1, 1, 1)
        self.checkBox_2 = QtWidgets.QCheckBox(settings_action_dialog)
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout.addWidget(self.checkBox_2, 10, 1, 1, 1)
        self.checkBox_3 = QtWidgets.QCheckBox(settings_action_dialog)
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout.addWidget(self.checkBox_3, 11, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(settings_action_dialog)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 8, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(settings_action_dialog)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 2, 1, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(settings_action_dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 25, 6, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(settings_action_dialog)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 5, 1, 1, 6)
        self.lineEdit_3 = QtWidgets.QLineEdit(settings_action_dialog)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 6, 1, 1, 6)
        self.lineEdit_2 = QtWidgets.QLineEdit(settings_action_dialog)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 7, 1, 1, 6)

        self.retranslateUi(settings_action_dialog)
        self.buttonBox.accepted.connect(settings_action_dialog.accept)
        self.buttonBox.rejected.connect(settings_action_dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(settings_action_dialog)

    def retranslateUi(self, settings_action_dialog):
        _translate = QtCore.QCoreApplication.translate
        settings_action_dialog.setWindowTitle(_translate("settings_action_dialog", "Dialog"))
        self.radioButton.setText(_translate("settings_action_dialog", "RadioButton"))
        self.label_4.setText(_translate("settings_action_dialog", "TextLabel"))
        self.checkBox_4.setText(_translate("settings_action_dialog", "CheckBox"))
        self.checkBox_6.setText(_translate("settings_action_dialog", "CheckBox"))
        self.radioButton_2.setText(_translate("settings_action_dialog", "RadioButton"))
        self.label_6.setText(_translate("settings_action_dialog", "TextLabel"))
        self.label.setText(_translate("settings_action_dialog", "TextLabel"))
        self.label_5.setText(_translate("settings_action_dialog", "TextLabel"))
        self.label_7.setText(_translate("settings_action_dialog", "TextLabel"))
        self.label_10.setText(_translate("settings_action_dialog", "TextLabel"))
        self.label_11.setText(_translate("settings_action_dialog", "TextLabel"))
        self.checkBox.setText(_translate("settings_action_dialog", "CheckBox"))
        self.label_3.setText(_translate("settings_action_dialog", "TextLabel"))
        self.label_9.setText(_translate("settings_action_dialog", "TextLabel"))
        self.checkBox_5.setText(_translate("settings_action_dialog", "CheckBox"))
        self.label_2.setText(_translate("settings_action_dialog", "TextLabel"))
        self.checkBox_2.setText(_translate("settings_action_dialog", "CheckBox"))
        self.checkBox_3.setText(_translate("settings_action_dialog", "CheckBox"))
        self.label_8.setText(_translate("settings_action_dialog", "TextLabel"))
        self.label_12.setText(_translate("settings_action_dialog", "TextLabel"))

