'\" t
.\"     Title: nagstamon
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.75.1 <http://docbook.sf.net/>
.\"      Date: 03/20/2010
.\"  Language: English
.\"
.TH "NAGSTAMON" "1" "03/20/2010"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
nagstamon \- Nagios status monitor which takes place in systray or on desktop
.SH "SYNOPSIS"
.sp
nagstamon [alternate\-config]
.SH "DESCRIPTION"
.sp
Nagstamon is a Nagios status monitor which takes place in systray or on desktop as floating statusbar to inform you in realtime about the status of your Nagios monitored network\&. Nagstamon connects to multiple Nagios, Opsview, Icinga, Centreon, Op5Monitor and Check_MK Multisite monitoring servers.\&.
.sp
The command can optionally take one argument giving the path to an alternate configuration file\&.
.SH "OPTIONS"
.sp
No options\&.
.SH "AUTHOR"
.sp
This manual page has been written by Carl Chenet <chaica@ohmytux\&.com>\&.
.SH "RESSOURCES"
.sp
http://sourceforge\&.net/projects/nagstamon/
.SH "LICENSE"
.sp
This manual page is licensed under the GPL\-2 license\&.

