name: play-with-windows-codesigning
on:
  push:
    tags-ignore: 'v*'
    branches:
      - '**'
      - '!master'
      - '!*.*.*'

jobs:
  windows-64:
    # better depend on stable build image
    runs-on: codesigning
    steps:
      - run: ls
