name: play-with-windows-codesigning
on:
  push:
    tags-ignore: 'v*'
    branches:
      - '**'
      - '!master'
      - '!*.*.*'

env:
  python_win_version: 3.14.7

jobs:
  windows-64:
    # better depend on stable build image
    runs-on: codesigning
    steps:
      - run: pwd
      - run: Get-ChildItem -Recurse
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: '${{ env.python_win_version }}'
          architecture: x64
